name: Deploy pages on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.142.0
          extended: true

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Build                                
        run: hugo

      - name: Deploy                               
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: bitrat/bitrat.github.io
          publish_branch: main
          # Without `keep_files` the `CNAME` file in the target repo will get removed
          # and the custom domain configured for GitHub pages will get dropped every 
          # time the action runs…
          keep_files: true
